name: Gradle Build and Test

on:
  push:
    branches: [ main, master ]
    paths:
      - 'drift-schema/**'
      - 'drift-api/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'drift-schema/**'
      - 'drift-api/**'
      - '.github/workflows/**'

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build and Test All Projects
        run: |
          chmod +x gradlew
          ./gradlew clean test jacocoTestReport

      - name: Generate Schema Coverage Badge
        uses: cicirello/jacoco-badge-generator@v2
        if: success()
        with:
          generate-branches-badge: true
          jacoco-csv-file: drift-schema/build/reports/jacoco/test/jacocoTestReport.csv
          badges-directory: .github/badges
          coverage-badge-filename: schema-coverage.svg
          branches-badge-filename: schema-branches.svg

      - name: Generate API Coverage Badge
        uses: cicirello/jacoco-badge-generator@v2
        if: success()
        with:
          generate-branches-badge: true
          jacoco-csv-file: drift-api/build/reports/jacoco/test/jacocoTestReport.csv
          badges-directory: .github/badges
          coverage-badge-filename: api-coverage.svg
          branches-badge-filename: api-branches.svg

      - name: Verify Reports
        run: |
          echo "Checking JaCoCo reports existence..."
          echo "Schema reports:"
          ls -la drift-schema/build/reports/jacoco/test/ || echo "Schema JaCoCo directory not found"
          echo "API reports:"
          ls -la drift-api/build/reports/jacoco/test/ || echo "API JaCoCo directory not found"

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            drift-schema/build/test-results/test/*.xml
            drift-api/build/test-results/test/*.xml

      - name: Upload Coverage Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            drift-schema/build/reports/jacoco/
            drift-api/build/reports/jacoco/
            .github/badges/

      - name: Update Badges
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .github/badges/*
          git commit -m "chore: update coverage badges" || echo "No changes to commit"
          git push || echo "No changes to push"