name: Gradle Build and Test

on:
  push:
    branches: [ main, master ]
    paths:
      - 'drift-schema/**'
      - 'drift-api/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'drift-schema/**'
      - 'drift-api/**'
      - '.github/workflows/**'

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  build-schema:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./drift-schema

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build and Test Schema
        run: |
          chmod +x gradlew
          ./gradlew clean test jacocoTestReport

      - name: Generate Schema Coverage Badge
        uses: cicirello/jacoco-badge-generator@v2
        if: always()
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          badges-directory: ../.github/badges
          coverage-badge-filename: schema-coverage.svg
          branches-badge-filename: schema-branches.svg

  build-api:
    runs-on: ubuntu-latest
    needs: build-schema
    defaults:
      run:
        working-directory: ./drift-api

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build and Test API
        run: |
          chmod +x gradlew
          ./gradlew clean test jacocoTestReport

      - name: Generate API Coverage Badge
        uses: cicirello/jacoco-badge-generator@v2
        if: always()
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          badges-directory: ../.github/badges
          coverage-badge-filename: api-coverage.svg
          branches-badge-filename: api-branches.svg

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            drift-schema/build/test-results/test/*.xml
            drift-api/build/test-results/test/*.xml

      - name: Upload Coverage Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            drift-schema/build/reports/jacoco/
            drift-api/build/reports/jacoco/
            .github/badges/